### PR TITLE
Add client side router

### PR DESCRIPTION
**Pull request by marcusgchan**
## Description

- Feel free to suggest other client side routers
- It seems that react router is a bit more opinionated now that it's used by remix
- I added a few additional routes for reference

Here's an example of fetching data from React Router docs:

image

### CODE REVIEW

**Comment by marcusgchan** [comment]
@dtemir can I get some feedback?

**Comment by dtemir** [comment]
hey! great work.

now, before I can merge this, can you tell me how you tested it? in other words, how do we know this works?

**Comment by marcusgchan** [comment]
```
const router = createBrowserRouter([
  { path: "/", element: <App /> },
  { path: "/experiences/create", element: <div>Create experience</div> },
  { path: "/experiences/:id", element: <div>View Specific experience</div> },
  { path: "/experiences/:id/edit", element: <div>Edit experience</div> },
]);
```

- Going to the root url should display ```<App />```
- "/experiences/create" should display ```<div>Create experience</div>```
- "/experience/<some-random-string>" should display ```<div>View Specific experience</div>```

- In the future those elements would be the actually pages but the pages aren't implemented yet

**Comment by dtemir** [comment]
Looks good to me!

**Pull request merged**
